### ISSUE TITLE
Custom docker images

### ISSUE THREAD

**Issue by nicholasjhenry** [civilcode/docker#1]
I propose we have our own docker base images for development and CI. This will allow us to benefit from docker by sharing layers across projects. In addition to this, we use the CircleCI docker image for Elixir which is based on Ubuntu, but we used Alpine. It would be great to use the same OS. This is what I'm thinking:

```
civilcode/elixir-dev
civilcode/elixir-ci
```
I propose we have the following images:

- `elixir-dev`: alpine-elixir base image with development environment
- `elixir-ci`: alpine-elixir base image for CircleCI

When we update, we increment the letter:

```
civilcode/elixir-dev:1.6.6a
civilcode/elixir-dev:1.6.6b
civilcode/elixir-dev:1.7.0b
```

@frahugo and @bokay I would like to know your thoughts about this approach.

**Comment by nicocharlery** [comment]
I would love to see that 👍🏾
That will also give us the ability to control the underlying versions of our technical stack (elixir / erlang / nodejs / gnumeric).

**Comment by nicocharlery** [comment]
FYI, we have this repo https://github.com/civilcode/docker-ma-base that we had published on our docker hub for a client (MA)
https://hub.docker.com/r/civilcode/docker-ma-base/

**Comment by frahugo** [comment]
:100: Yes. Lets go with our own images.

**Comment by nicholasjhenry** [comment]
Handled in #2
